### ISSUE TITLE
Failed. Audio file not found / Can't decode audio file

### ISSUE THREAD

**Issue by mnm-isola** [MikiraSora/BmsPreviewAudioGenerator#8]
With special character in filepath:
```
E:\bms\BmsPreviewAudioGenerator.0.9.5>BmsPreviewAudioGenerator.exe -batch -path="E:\bms\jukebox\BOF2011\[BOF2011]cittan_leviathan_bms_ogg[ぬるぽホールディングス]" -start="20000" -end="40000" -fade_out="1000" -save_name="preview_bms.ogg" -fast_clip -process_buffer_size="2500000" -support_extend_format
Program version:0.9.5.0
Init BASS successfully.
------- 1/1 (100.00%)   -------
BMS file path:E:\bms\jukebox\BOF2011\[BOF2011]cittan_leviathan_bms_ogg[ぬるぽホールディングス]\leviathan_sp_another.bms
BMSファイル解析開始 :E:\bms\jukebox\BOF2011\[BOF2011]cittan_leviathan_bms_ogg[ぬるぽホールディングス]\leviathan_sp_another.bms
BMSデータ解析時間(ms) :0
BMSファイル解析完了 :E:\bms\jukebox\BOF2011\[BOF2011]cittan_leviathan_bms_ogg[ぬるぽホールディングス]\leviathan_sp_another.bms - TimeLine数:862
Failed.
Can't decode audio file : E:\bms\jukebox\BOF2011\[BOF2011]cittan_leviathan_bms_ogg[ぬるぽホールディングス]\leviathan_sp_another.bms
   at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.<GeneratePreviewAudio>g__LoadAudio|0(String audioFilePath)
   at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.<GeneratePreviewAudio>b__7(ValueTuple`2 x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at BmsPreviewAudioGenerator.Program.GeneratePreviewAudio(String dir_path, String specific_bms_file_name, String start_time, String end_time, String encoder_command_line, String save_file_name, Int32 fade_out, Int32 fade_in, Boolean check_vaild, Boolean fast_clip, Boolean no_skip, SupportEncodingType encoding_type)



Generate failed list(1):
E:\bms\jukebox\BOF2011\[BOF2011]cittan_leviathan_bms_ogg[ぬるぽホールディングス]
```

Without special character in filepath:
```
E:\bms\BmsPreviewAudioGenerator.0.9.5>BmsPreviewAudioGenerator.exe -batch -path="E:\bms\jukebox\G2R2014\watercolored" -start="20000" -end="40000" -fade_out="1000" -save_name="preview_bms.ogg" -fast_clip -process_buffer_size="2500000" -support_extend_format
Program version:0.9.5.0
Init BASS successfully.
------- 1/1 (100.00%)   -------
BMS file path:E:\bms\jukebox\G2R2014\watercolored\sph.bms
BMSファイル解析開始 :E:\bms\jukebox\G2R2014\watercolored\sph.bms
BMSデータ解析時間(ms) :0
BMSファイル解析完了 :E:\bms\jukebox\G2R2014\watercolored\sph.bms - TimeLine数:556
Failed.
Audio file not found:
   at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.<GeneratePreviewAudio>g__LoadAudio|0(String audioFilePath)
   at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.<GeneratePreviewAudio>b__7(ValueTuple`2 x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at BmsPreviewAudioGenerator.Program.GeneratePreviewAudio(String dir_path, String specific_bms_file_name, String start_time, String end_time, String encoder_command_line, String save_file_name, Int32 fade_out, Int32 fade_in, Boolean check_vaild, Boolean fast_clip, Boolean no_skip, SupportEncodingType encoding_type)



Generate failed list(1):
E:\bms\jukebox\G2R2014\watercolored
```
There are around 900 bms charts which the program did not process. Here's the list.
[New Text Document (2).txt](https://github.com/MikiraSora/BmsPreviewAudioGenerator/files/8726156/New.Text.Document.2.txt)

**Comment by MikiraSora** [comment]
Could you provide some bms folders you got failed.

**Comment by mnm-isola** [comment]
> 

https://drive.google.com/drive/folders/1auosHqZnlOwwgA98739EvjNOotav7KFA?usp=sharing

**Comment by MikiraSora** [comment]
https://github.com/MikiraSora/BmsPreviewAudioGenerator/releases/tag/v0.9.6
try again

**Comment by mnm-isola** [comment]
Works now for Ted_Lorikeet_ogg and Milk, still not working for 3rd Avenue.
Ran the new version over my BOF2009 folder and there are still some bms that cause errors. [log here](https://github.com/MikiraSora/BmsPreviewAudioGenerator/files/8730396/New.Text.Document.txt)

Also added more samples in the google drive link for your investigation.

**Comment by MikiraSora** [comment]
![image](https://user-images.githubusercontent.com/7549173/172216838-1e4fbe05-0fd4-49f9-87ea-460cc351c18a.png)


fixed https://github.com/MikiraSora/BmsPreviewAudioGenerator/releases/tag/v0.9.7

**Comment by Ceynou** [comment]
with v0.9.7
> Generate failed list(19):
.\arabianfunkot
.\ascension
.\cheerly_waveform
.\froshtrance
.\frost_pop
.\gothic_electric
.\grandfinale
.\island
.\juvenile_fantasia
.\komoriuta_ex
.\rockin_drumnbass
.\saxual_rave
.\sf_gabba
.\skapop
.\snowdrumnbass
.\teabreak
.\thanatos2011
.\ultemo
.\vapor

> BMSファイル解析完了 :.\teabreak\00_cinnamonteabreak_5btn.pms - TimeLine数:1141
Failed.
Audio file not found:  (hintDataPath : GtLR_122.ogg)
   at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.<GeneratePreviewAudio>g__LoadAudio|0(String audioFilePath, String hintDataPath)
   at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.<GeneratePreviewAudio>b__7(ValueTuple`3 x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at BmsPreviewAudioGenerator.Program.GeneratePreviewAudio(String dir_path, String specific_bms_file_name, String start_time, String end_time, String encoder_command_line, String save_file_name, Int32 fade_out, Int32 fade_in, Boolean check_vaild, Boolean fast_clip, Boolean no_skip, SupportEncodingType encoding_type, Boolean ignore_audio_missing)

no error with v0.8.8 _(I renamed the .pms to .bms obviously)_
> Generate failed list(0):

**Comment by MikiraSora** [comment]
> with v0.9.7
> 
> > Generate failed list(19):
> > .\arabianfunkot
> > .\ascension
> > .\cheerly_waveform
> > .\froshtrance
> > .\frost_pop
> > .\gothic_electric
> > .\grandfinale
> > .\island
> > .\juvenile_fantasia
> > .\komoriuta_ex
> > .\rockin_drumnbass
> > .\saxual_rave
> > .\sf_gabba
> > .\skapop
> > .\snowdrumnbass
> > .\teabreak
> > .\thanatos2011
> > .\ultemo
> > .\vapor
> 
> > BMSファイル解析完了 :.\teabreak\00_cinnamonteabreak_5btn.pms - TimeLine数:1141
> > Failed.
> > Audio file not found:  (hintDataPath : GtLR_122.ogg)
> > at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.g__LoadAudio|0(String audioFilePath, String hintDataPath)
> > at BmsPreviewAudioGenerator.Program.<>c__DisplayClass10_0.b__7(ValueTuple`3 x)    at System.Linq.Utilities.<>c__DisplayClass2_0`3.b__0(TSource x)
> > at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
> > at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
> > at BmsPreviewAudioGenerator.Program.GeneratePreviewAudio(String dir_path, String specific_bms_file_name, String start_time, String end_time, String encoder_command_line, String save_file_name, Int32 fade_out, Int32 fade_in, Boolean check_vaild, Boolean fast_clip, Boolean no_skip, SupportEncodingType encoding_type, Boolean ignore_audio_missing)
> 
> no error with v0.8.8 _(I renamed the .pms to .bms obviously)_
> 
> > Generate failed list(0):

Did you check these audio (which reported missing) are actual exist in BMS folder?
and please provide these folders. :D

**Comment by Ceynou** [comment]
if it worked with the v0.8.8 then it's not missing any audio file is it? the pack is there, this is not meant to be played anywhere else than on their player, I'm not gonna provide the pms files that I extracted(very easy to do)
https://tm3.toymusical.net/download.html

**Comment by MikiraSora** [comment]
> if it worked with the v0.8.8 then it's not missing any audio file is it? the pack is there, this is not meant to be played anywhere else than on their player, I'm not gonna provide the pms files that I extracted(very easy to do) https://tm3.toymusical.net/download.html

![image](https://user-images.githubusercontent.com/7549173/172898213-4e0561d2-28d2-4372-8ec5-163be4b102e0.png)
all right, maybe program have to ignore missing audio file as default.

**Comment by Ceynou** [comment]
waaaaait so it was really missing audio files, I should have listened and checked sorry, okay, I guess now I can suggest to add a parameter to throw an error when audio files are missing? something like -no_missing_error

**Comment by MikiraSora** [comment]
> waaaaait so it was really missing audio files, I should have listened and checked sorry, okay, I guess now I can suggest to add a parameter to throw an error when audio files are missing? something like -no_missing_error

before 0.9.7 there is a `ignore_audio_missing` switch parameter to ignore missing audio file.
but 0.9.8 now , program will ignore missing audio file by default (until you add `check_audio_missing` switch parameter)

**Comment by Ceynou** [comment]
Thank you very much for your patience and for the update, have a great day!
